# Generated by Django 2.0.6 on 2018-06-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_db_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_info',
            name='db_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
