# Generated by Django 2.0.6 on 2018-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_db_info_db_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=32)),
                ('log_time', models.CharField(max_length=255)),
            ],
        ),
    ]
