# Generated by Django 2.0.6 on 2018-06-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_log_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_info',
            old_name='user_name',
            new_name='log_user',
        ),
    ]
